package app;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Matriz;

/**
 *
 * @author David Medina Garcia
 */
public class AppMatrices extends javax.swing.JFrame {

    // declaracion de objetos
    Matriz matrizA = null;
    Matriz matrizB = null;

    /**
     * Creates new form AppMatrices
     */
    public AppMatrices() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDimension = new javax.swing.JTextField();
        btnLimpiarA = new javax.swing.JButton();
        btnLlenarA = new javax.swing.JButton();
        btnLimpiarB = new javax.swing.JButton();
        btnLlenarB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMatrizA = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMatrizB = new javax.swing.JTable();
        btnDiagonalA = new javax.swing.JButton();
        btnDiagonalB = new javax.swing.JButton();
        txtDiagonalA = new javax.swing.JTextField();
        txtDiagonalB = new javax.swing.JTextField();
        btnTranspuestaA = new javax.swing.JButton();
        btnTanspuestaB = new javax.swing.JButton();
        btnSumaMatrices = new javax.swing.JButton();
        btnMultMatrices = new javax.swing.JButton();
        btnLimpiarResultado = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSuma = new javax.swing.JToggleButton();
        cmbMatriz = new javax.swing.JComboBox<>();
        cmbFilaColumna = new javax.swing.JComboBox<>();
        cmbNroFilaColumna = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        txtSuma = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableResultado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DIMENSION DE LAS MATRICES");

        txtDimension.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDimension.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDimensionFocusLost(evt);
            }
        });
        txtDimension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDimensionActionPerformed(evt);
            }
        });

        btnLimpiarA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiarA.setForeground(new java.awt.Color(153, 0, 153));
        btnLimpiarA.setText("Limpiar A");
        btnLimpiarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarAActionPerformed(evt);
            }
        });

        btnLlenarA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLlenarA.setForeground(new java.awt.Color(153, 0, 153));
        btnLlenarA.setText("Llenar A");
        btnLlenarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlenarAActionPerformed(evt);
            }
        });

        btnLimpiarB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiarB.setForeground(new java.awt.Color(0, 0, 204));
        btnLimpiarB.setText("Limpiar B");
        btnLimpiarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarBActionPerformed(evt);
            }
        });

        btnLlenarB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLlenarB.setForeground(new java.awt.Color(0, 0, 204));
        btnLlenarB.setText("Llenar B");
        btnLlenarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlenarBActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Matriz A");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Matriz B");

        jTableMatrizA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableMatrizA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMatrizA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableMatrizA.setEnabled(false);
        jTableMatrizA.setGridColor(new java.awt.Color(204, 153, 255));
        jTableMatrizA.setShowGrid(true);
        jScrollPane1.setViewportView(jTableMatrizA);

        jTableMatrizB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableMatrizB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMatrizB.setEnabled(false);
        jTableMatrizB.setGridColor(new java.awt.Color(153, 153, 255));
        jTableMatrizB.setShowGrid(true);
        jScrollPane2.setViewportView(jTableMatrizB);

        btnDiagonalA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDiagonalA.setForeground(new java.awt.Color(153, 0, 153));
        btnDiagonalA.setText("Diagonal A");
        btnDiagonalA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagonalAActionPerformed(evt);
            }
        });

        btnDiagonalB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDiagonalB.setForeground(new java.awt.Color(0, 0, 204));
        btnDiagonalB.setText("Diagonal B");
        btnDiagonalB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagonalBActionPerformed(evt);
            }
        });

        txtDiagonalA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiagonalAActionPerformed(evt);
            }
        });

        btnTranspuestaA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTranspuestaA.setText("Transpuesta A");
        btnTranspuestaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranspuestaAActionPerformed(evt);
            }
        });

        btnTanspuestaB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTanspuestaB.setText("Transpuesta B");
        btnTanspuestaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanspuestaBActionPerformed(evt);
            }
        });

        btnSumaMatrices.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSumaMatrices.setText("A + B");
        btnSumaMatrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaMatricesActionPerformed(evt);
            }
        });

        btnMultMatrices.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMultMatrices.setText("A * B");
        btnMultMatrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultMatricesActionPerformed(evt);
            }
        });

        btnLimpiarResultado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiarResultado.setForeground(new java.awt.Color(255, 51, 0));
        btnLimpiarResultado.setText("Limpiar");
        btnLimpiarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarResultadoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Matriz resultado:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Matriz");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Elegir");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Numero");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("SUMA");

        btnSuma.setBackground(new java.awt.Color(255, 153, 153));
        btnSuma.setText("Visualizar Suma");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        cmbMatriz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matriz A", "Matriz B" }));
        cmbMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMatrizActionPerformed(evt);
            }
        });

        cmbFilaColumna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fila", "Columna" }));
        cmbFilaColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilaColumnaActionPerformed(evt);
            }
        });

        cmbNroFilaColumna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        cmbNroFilaColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNroFilaColumnaActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 204, 153));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSumaActionPerformed(evt);
            }
        });

        jTableResultado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableResultado.setEnabled(false);
        jTableResultado.setGridColor(new java.awt.Color(255, 153, 153));
        jTableResultado.setShowGrid(true);
        jScrollPane4.setViewportView(jTableResultado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnTanspuestaB, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSumaMatrices, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnMultMatrices, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTranspuestaA, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(271, 271, 271)
                            .addComponent(btnLimpiarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel7)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel8)
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(171, 171, 171)
                            .addComponent(jLabel1)
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDimension, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnDiagonalB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDiagonalB, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnLimpiarB)
                                            .addGap(68, 68, 68)
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnLlenarB))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(186, 186, 186)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(194, 194, 194)
                                            .addComponent(jLabel4)))
                                    .addGap(114, 114, 114)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbFilaColumna, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbNroFilaColumna, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnDiagonalA, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDiagonalA, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnLimpiarA)
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel2)
                                        .addGap(70, 70, 70)
                                        .addComponent(btnLlenarA))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDimension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarA)
                    .addComponent(btnLlenarA)
                    .addComponent(btnLimpiarB)
                    .addComponent(btnLlenarB)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnDiagonalB)
                                .addComponent(txtDiagonalB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnDiagonalA))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDiagonalA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiarResultado)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(cmbFilaColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(cmbNroFilaColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(btnSuma)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(txtSuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnTranspuestaA)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnTanspuestaB)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSumaMatrices)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnMultMatrices)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMatrizActionPerformed
    }//GEN-LAST:event_cmbMatrizActionPerformed

    private void btnSumaMatricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaMatricesActionPerformed
        // Verificamos si alguna de las matrices es nula
        if (matrizB == null || matrizA == null) {
            JOptionPane.showMessageDialog(this, "Las matrices no tienen valores");
        } else if (matrizA.getDimension() != matrizB.getDimension()) { // Verificamos si las matrices tienen la misma dimensión
            JOptionPane.showMessageDialog(this, "Las matrices no tienen la misma dimensión");
        } else {
            // Si ambas matrices tienen valores y tienen la misma dimensión, realizamos la suma
            Matriz suma = matrizA.suma(matrizB);
            // Llenamos la tabla con el resultado de la suma
            llenarjTable(suma, jTableResultado);
        }

    }//GEN-LAST:event_btnSumaMatricesActionPerformed

    private void txtDiagonalAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagonalAActionPerformed

    }//GEN-LAST:event_txtDiagonalAActionPerformed

    private void txtDimensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDimensionActionPerformed

    }//GEN-LAST:event_txtDimensionActionPerformed

    private void txtDimensionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDimensionFocusLost


    }//GEN-LAST:event_txtDimensionFocusLost

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Mostramos un cuadro de diálogo de confirmación para preguntar si se quiere salir del programa
        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Quieres salir del programa?",
                "Salir",
                JOptionPane.YES_NO_OPTION);

        // Verificamos la respuesta del usuario
        if (confirmacion == JOptionPane.YES_OPTION) {
            // Si la respuesta es sí, cerramos el programa
            System.exit(0);
        }


    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLlenarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlenarAActionPerformed
        // Verificamos si el campo de texto de la dimensión está vacío
        if (txtDimension.getText().isBlank()) {
            // Si está vacío, mostramos un mensaje de error y enfocamos el campo de texto
            JOptionPane.showMessageDialog(this, "ERROR!! Dimensión no tiene valor");
            txtDimension.requestFocus();
        } else {
            try {
                // Convertimos el texto a un entero
                int dimension = Integer.parseInt(txtDimension.getText());

                // Verificamos si la dimensión está dentro del rango permitido
                if (dimension < 1 || dimension > Matriz.DIMENSION_MAX) {
                    // Si no está en el rango permitido, mostramos un mensaje de error y enfocamos el campo de texto
                    JOptionPane.showMessageDialog(this, "La dimensión de las matrices no puede ser 0 o superior a " + Matriz.DIMENSION_MAX);
                    txtDimension.requestFocus();
                } else {
                    // Si la dimensión está dentro del rango permitido, creamos una nueva matriz con esa dimensión
                    matrizA = new Matriz(dimension);
                    // Llenamos la tabla jTableMatrizA con la nueva matriz
                    llenarjTable(matrizA, jTableMatrizA);
                }
            } catch (NumberFormatException e) {
                // Capturamos cualquier excepción de formato numérico
                System.out.println("La dimensión de las matrices no puede estar vacía");
            }
        }

    }//GEN-LAST:event_btnLlenarAActionPerformed

    private void btnLlenarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlenarBActionPerformed
        // Verificamos si el campo de texto de la dimensión está vacío
        if (txtDimension.getText().isBlank()) {
            // Si está vacío, mostramos un mensaje de error y enfocamos el campo de texto
            JOptionPane.showMessageDialog(this, "ERROR!! Dimensión no tiene valor");
            txtDimension.requestFocus();
        } else {
            try {
                // Convertimos el texto a un entero
                int dimension = Integer.parseInt(txtDimension.getText());

                // Validamos la dimensión utilizando el método estático validarDimension() de la clase Matriz
                if (!Matriz.validarDimension(dimension)) {
                    // Si la dimensión no es válida, mostramos un mensaje de error y enfocamos el campo de texto
                    JOptionPane.showMessageDialog(this, "La dimensión de las matrices no puede ser 0 o superior a " + Matriz.DIMENSION_MAX);
                    txtDimension.requestFocus();
                } else {
                    // Si la dimensión es válida, creamos una nueva matriz con esa dimensión
                    matrizB = new Matriz(dimension);
                    // Llenamos la tabla jTableMatrizB con la nueva matriz
                    llenarjTable(matrizB, jTableMatrizB);
                }
            } catch (NumberFormatException e) {
                // Capturamos cualquier excepción de formato numérico
                System.out.println("La dimensión de las matrices no puede estar vacía");
            }
        }

    }//GEN-LAST:event_btnLlenarBActionPerformed

    private void btnLimpiarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarAActionPerformed
        limpiarjTable(jTableMatrizA);
        matrizA = null;
    }//GEN-LAST:event_btnLimpiarAActionPerformed

    private void btnLimpiarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarBActionPerformed
        limpiarjTable(jTableMatrizB);
        matrizB = null;
    }//GEN-LAST:event_btnLimpiarBActionPerformed

    private void btnDiagonalAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagonalAActionPerformed
        if (matrizA == null) {
            JOptionPane.showMessageDialog(this, "La matriz A no tiene datos");
            txtDimension.requestFocus();
        } else {
            txtDiagonalA.setText(Integer.toString(matrizA.diagonal()));
        }
    }//GEN-LAST:event_btnDiagonalAActionPerformed

    private void btnDiagonalBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagonalBActionPerformed
        if (matrizB == null) {
            JOptionPane.showMessageDialog(this, "La matriz B no tiene datos");
            txtDimension.requestFocus();
        } else {
            txtDiagonalB.setText(Integer.toString(matrizB.diagonal()));
        }
    }//GEN-LAST:event_btnDiagonalBActionPerformed

    private void btnTranspuestaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranspuestaAActionPerformed
        if (matrizA == null) {
            JOptionPane.showMessageDialog(this, "La matriz A no tiene datos");
            txtDimension.requestFocus();
        } else {
            Matriz transpuesta = matrizA.transpuesta();
            llenarjTable(transpuesta, jTableResultado);
        }

    }//GEN-LAST:event_btnTranspuestaAActionPerformed

    private void btnTanspuestaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanspuestaBActionPerformed
        if (matrizB == null) {
            JOptionPane.showMessageDialog(this, "La matriz B no tiene datos");
            txtDimension.requestFocus();
        } else {
            Matriz transpuesta = matrizB.transpuesta();
            llenarjTable(transpuesta, jTableResultado);
        }
    }//GEN-LAST:event_btnTanspuestaBActionPerformed

    private void btnMultMatricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultMatricesActionPerformed
        if (matrizB == null || matrizA == null) {
            JOptionPane.showMessageDialog(this, "Las matrices no tienen valores");
        } else if (matrizA.getDimension() != matrizB.getDimension()) {
            JOptionPane.showMessageDialog(this, "Las matrices no tienen la misma dimension");
        } else {
            Matriz mult = matrizA.multiplicar(matrizB);
            llenarjTable(mult, jTableResultado);
        }
    }//GEN-LAST:event_btnMultMatricesActionPerformed

    private void cmbFilaColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilaColumnaActionPerformed
    }//GEN-LAST:event_cmbFilaColumnaActionPerformed

    private void cmbNroFilaColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNroFilaColumnaActionPerformed

    }//GEN-LAST:event_cmbNroFilaColumnaActionPerformed

    private void txtSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSumaActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        try {
            // Obtenemos el nombre de la matriz seleccionada en el ComboBox
            String matriz = cmbMatriz.getSelectedItem().toString();
            // Obtenemos el nombre de la opción seleccionada en el ComboBox (fila o columna)
            String filaColumna = cmbFilaColumna.getSelectedItem().toString();
            // Obtenemos el índice de la opción seleccionada en el ComboBox (que va de 0 a 6)
            int nroFilaColumna = cmbNroFilaColumna.getSelectedIndex();

            // Verificamos si el número de fila o columna seleccionado es mayor que la dimensión de las matrices
            if (nroFilaColumna > Integer.parseInt(txtDimension.getText())) {
                JOptionPane.showMessageDialog(this, "El número elegido no puede ser mayor que la dimensión de las matrices");
            } else {
                if (matriz.equalsIgnoreCase("Matriz A")) {
                    // Verificamos si la matriz A está vacía
                    if (matrizA == null) {
                        JOptionPane.showMessageDialog(this, "La matriz A no tiene datos");
                        txtDimension.requestFocus();
                        return; // Salimos del método
                    }
                    // Verificamos si se seleccionó sumar una fila o una columna
                    if (filaColumna.equalsIgnoreCase("fila")) {
                        // Si se seleccionó sumar una fila, mostramos la suma en el campo de texto txtSuma
                        txtSuma.setText(Integer.toString(matrizA.sumaFila(nroFilaColumna)));
                    } else {
                        // Si se seleccionó sumar una columna, mostramos la suma en el campo de texto txtSuma
                        txtSuma.setText(Integer.toString(matrizA.sumaColumna(nroFilaColumna)));
                    }
                } else {
                    // Verificamos si la matriz B está vacía
                    if (matrizB == null) {
                        JOptionPane.showMessageDialog(this, "La matriz B no tiene datos");
                        txtDimension.requestFocus();
                        return; // Salimos del método
                    }
                    // Verificamos si se seleccionó sumar una fila o una columna
                    if (filaColumna.equalsIgnoreCase("fila")) {
                        // Si se seleccionó sumar una fila, mostramos la suma en el campo de texto txtSuma
                        txtSuma.setText(Integer.toString(matrizB.sumaFila(nroFilaColumna)));
                    } else {
                        // Si se seleccionó sumar una columna, mostramos la suma en el campo de texto txtSuma
                        txtSuma.setText(Integer.toString(matrizB.sumaColumna(nroFilaColumna)));
                    }
                }
            }
        } catch (HeadlessException | NumberFormatException e) {
            // Capturamos cualquier excepción de formato numérico o de entorno gráfico
            JOptionPane.showMessageDialog(this, "ERROR!! Dimensión no tiene valor");
            txtDimension.requestFocus();
        }

    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnLimpiarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarResultadoActionPerformed
        limpiarjTable(jTableResultado);
    }//GEN-LAST:event_btnLimpiarResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppMatrices.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppMatrices.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppMatrices.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppMatrices.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppMatrices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiagonalA;
    private javax.swing.JButton btnDiagonalB;
    private javax.swing.JButton btnLimpiarA;
    private javax.swing.JButton btnLimpiarB;
    private javax.swing.JButton btnLimpiarResultado;
    private javax.swing.JButton btnLlenarA;
    private javax.swing.JButton btnLlenarB;
    private javax.swing.JButton btnMultMatrices;
    private javax.swing.JButton btnSalir;
    private javax.swing.JToggleButton btnSuma;
    private javax.swing.JButton btnSumaMatrices;
    private javax.swing.JButton btnTanspuestaB;
    private javax.swing.JButton btnTranspuestaA;
    private javax.swing.JComboBox<String> cmbFilaColumna;
    private javax.swing.JComboBox<String> cmbMatriz;
    private javax.swing.JComboBox<String> cmbNroFilaColumna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableMatrizA;
    private javax.swing.JTable jTableMatrizB;
    private javax.swing.JTable jTableResultado;
    private javax.swing.JTextField txtDiagonalA;
    private javax.swing.JTextField txtDiagonalB;
    private javax.swing.JTextField txtDimension;
    private javax.swing.JTextField txtSuma;
    // End of variables declaration//GEN-END:variables

    // Método para llenar una tabla (JTable) con los datos de una matriz
    private void llenarjTable(Matriz m, JTable jt) {
        // Obtenemos la matriz de la instancia de la clase Matriz
        int[][] matriz = m.getMatriz();
        // Obtenemos la dimensión de la matriz
        int dimension = m.getDimension();
        // Creamos un nuevo modelo de tabla (DefaultTableModel) con la dimensión de la matriz
        DefaultTableModel model = new DefaultTableModel(dimension, dimension);

        // Iteramos sobre las filas de la matriz
        for (int i = 0; i < dimension; i++) {
            // Iteramos sobre las columnas de la matriz
            for (int j = 0; j < dimension; j++) {
                // Establecemos el valor de la celda en la posición (i, j) con el valor correspondiente de la matriz
                model.setValueAt(matriz[i][j], i, j);
            }
        }

        // Establecemos el modelo de tabla creado en la tabla proporcionada
        jt.setModel(model);
    }

    // limpiamos las tablas
    private void limpiarjTable(JTable jt) {
        DefaultTableModel model = (DefaultTableModel) jt.getModel();

        int rowCount = model.getRowCount();
        int columnCount = model.getColumnCount();

        for (int i = 0; i < rowCount; i++) {
            for (int j = 0; j < columnCount; j++) {
                model.setValueAt("", i, j);
            }
        }
    }

}
