package app;

import controlador.OperacionesFichero;
import enumTipoMueble.TipoMueble;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;
import modelos.Mueble;
import validaciones.Validacion;

/**
 *
 * @author David Medina Garcia
 */
public class AppGestionMueblesDavid extends javax.swing.JFrame {

    /**
     * Creates new form AppGestionMueblesDavid
     */
    public AppGestionMueblesDavid() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDescrpMueble = new javax.swing.JTextField();
        txtPrecioUnitario = new javax.swing.JTextField();
        txtUnidadesAlmacen = new javax.swing.JTextField();
        txtUnidadesMinimas = new javax.swing.JTextField();
        cmbTipoMueble = new javax.swing.JComboBox<>();
        btnLimpiarMuebles = new javax.swing.JButton();
        btnVisualizarMuebles = new javax.swing.JButton();
        btnEliminarMueble = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnEliminarTodos = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTxt = new javax.swing.JTextArea();
        btnSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Codigo Mueble");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Descripcion Mueble");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Precio Unitario");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Unidades Almacen");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Unidades Minimas");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tipo Mueble");

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFocusLost(evt);
            }
        });

        txtDescrpMueble.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescrpMueble.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescrpMuebleFocusLost(evt);
            }
        });

        txtPrecioUnitario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrecioUnitario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioUnitarioFocusLost(evt);
            }
        });
        txtPrecioUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioUnitarioActionPerformed(evt);
            }
        });

        txtUnidadesAlmacen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUnidadesAlmacen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUnidadesAlmacenFocusLost(evt);
            }
        });

        txtUnidadesMinimas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUnidadesMinimas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUnidadesMinimasFocusLost(evt);
            }
        });

        cmbTipoMueble.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipoMueble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno", "Hogar", "Despacho", "Colegios" }));
        cmbTipoMueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoMuebleActionPerformed(evt);
            }
        });

        btnLimpiarMuebles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiarMuebles.setText("LIMPIAR MUEBLES");
        btnLimpiarMuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarMueblesActionPerformed(evt);
            }
        });

        btnVisualizarMuebles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVisualizarMuebles.setText("VISUALIZAR MUEBLES");
        btnVisualizarMuebles.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnVisualizarMueblesFocusLost(evt);
            }
        });
        btnVisualizarMuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarMueblesActionPerformed(evt);
            }
        });

        btnEliminarMueble.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminarMueble.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarMueble.setText("Eliminar Mueble");
        btnEliminarMueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMuebleActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGrabar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnEliminarTodos.setBackground(new java.awt.Color(204, 0, 51));
        btnEliminarTodos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarTodos.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarTodos.setText("Eliminar Todos");
        btnEliminarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodosActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        areaTxt.setEditable(false);
        areaTxt.setColumns(20);
        areaTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areaTxt.setRows(5);
        jScrollPane1.setViewportView(areaTxt);

        btnSalir.setBackground(new java.awt.Color(0, 51, 204));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("PRECIO");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("CODIGO");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("DESCRIPCION");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("UNIDADES ALMACEN");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("TIPO MUEBLE");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("UNIDADES MINIMAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel9)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescrpMueble, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                            .addComponent(txtUnidadesAlmacen)
                            .addComponent(txtUnidadesMinimas)
                            .addComponent(cmbTipoMueble, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addComponent(btnEliminarMueble, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addComponent(btnEliminarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                            .addComponent(btnGrabar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addComponent(btnLimpiarMuebles)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnVisualizarMuebles))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtDescrpMueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGrabar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarMueble)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarTodos))
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUnidadesAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUnidadesMinimas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTipoMueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarMuebles)
                    .addComponent(btnVisualizarMuebles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoMuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoMuebleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoMuebleActionPerformed

    private void btnVisualizarMueblesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnVisualizarMueblesFocusLost


    }//GEN-LAST:event_btnVisualizarMueblesFocusLost

    private void txtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusLost
        if (txtCodigo.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "¡ERROR! El codigo no puede estar vacío.");
        } else {
            try {
                int num = Integer.parseInt(txtCodigo.getText());
                if (!Validacion.validacionNumeros(num)) {
                    JOptionPane.showMessageDialog(this, "¡ERROR! El codigo debe ser un número entero de 5 cifras como maximo.");
                }

            } catch (InputMismatchException | NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "¡ERROR! El codigo debe ser un número entero de 5 cifras como maximo.");
            }
        }

    }//GEN-LAST:event_txtCodigoFocusLost

    private void txtDescrpMuebleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescrpMuebleFocusLost
        String descripcion = txtDescrpMueble.getText();
        if (!Validacion.validacionCadena(descripcion)) {
            JOptionPane.showMessageDialog(this, "¡ERROR! La descripción no puede estar vacía y no debe exceder los 15 caracteres.");
        }
    }//GEN-LAST:event_txtDescrpMuebleFocusLost

    private void txtPrecioUnitarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioUnitarioFocusLost
        if (txtPrecioUnitario.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "¡ERROR! El precio no puede estar vacío.");
        } else {
            try {
                double precio = Double.parseDouble(txtPrecioUnitario.getText());
                if (!Validacion.validacionPrecio(precio)) {
                    JOptionPane.showMessageDialog(null, "ERROR! El precio no puede estar vacío y debe ser mayor que 0 y tener dos decimales.");
                }
            } catch (InputMismatchException | NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "ERROR! El precio no puede estar vacío y debe ser mayor que 0 y tener dos decimales.");
            }
        }
    }//GEN-LAST:event_txtPrecioUnitarioFocusLost

    private void txtUnidadesAlmacenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnidadesAlmacenFocusLost
        if (txtUnidadesAlmacen.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "¡ERROR! Las unidades del almacen no pueden estar vacias");
        } else {
            try {
                int unidades = Integer.parseInt(txtUnidadesAlmacen.getText());
                if (!Validacion.validacionNumeros(unidades)) {
                    JOptionPane.showMessageDialog(this, "¡ERROR! Las unidades del almacen deben ser un número entero.");
                }
            } catch (InputMismatchException | NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "¡ERROR! Las unidades del almacen deben ser un número entero.");
            }
        }

    }//GEN-LAST:event_txtUnidadesAlmacenFocusLost

    private void txtUnidadesMinimasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnidadesMinimasFocusLost
        if (txtUnidadesMinimas.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "¡ERROR! Las unidades mínimas no pueden estar vacías.");
        } else {
            try {
                int unidades = Integer.parseInt(txtUnidadesMinimas.getText());
                if (!Validacion.validacionNumeros(unidades)) {
                    JOptionPane.showMessageDialog(this, "¡ERROR! Las unidades mínimas deben ser un número entero.");
                }
            } catch (InputMismatchException | NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "¡ERROR! Las unidades mínimas deben ser un número entero.");
            }
        }

    }//GEN-LAST:event_txtUnidadesMinimasFocusLost

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        try {
            // Validar si el campo txtCodigo está vacío
            if (txtCodigo.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "El codigo no puede estar vacío.");
                txtCodigo.requestFocus();
                return;
            }

            // Obtener el valor del campo txtCodigo
            int codigoMueble = Integer.parseInt(txtCodigo.getText());

            // Verificar si ya existe un registro con el mismo código
            if (OperacionesFichero.existeRegistro(codigoMueble)) {
                JOptionPane.showMessageDialog(this, "El codigo ya existe.");
                txtCodigo.requestFocus();
                return;
            }

            // almacenamos los campos en variables que se pasaran al objeto
            // convertimos a numero los campos necesarios
            String descripMueble = txtDescrpMueble.getText();
            double precioMueble = Double.parseDouble(txtPrecioUnitario.getText());
            int unidadesAlmacen = Integer.parseInt(txtUnidadesAlmacen.getText());
            int unidadesMinimas = Integer.parseInt(txtUnidadesMinimas.getText());
            // Validar el tipo de mueble seleccionado
            String elegirMueble = cmbTipoMueble.getSelectedItem().toString();
            TipoMueble tipoMueble = null;
            switch (elegirMueble) {
                case "Hogar":
                    tipoMueble = TipoMueble.H;
                    break;
                case "Despacho":
                    tipoMueble = TipoMueble.D;
                    break;
                case "Colegios":
                    tipoMueble = TipoMueble.C;
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Debe elegir un tipo de mueble.");
                    return;
            }

            // comprobar que las unidades de almacen sean superiores a las unidades minimas
            if (!Validacion.validacionUnidades(unidadesAlmacen, unidadesMinimas)) {
                JOptionPane.showMessageDialog(this, "Las unidades de almacen no pueden ser inferiores a las unidades minimas.");
                return;
            }

            // Validamos una vez mas los campos para asegurarnos que no se graben datos incorrectos en el archivo
            if (!Validacion.validacionCadena(descripMueble)
                    || !Validacion.validacionNumeros(codigoMueble)
                    || !Validacion.validacionPrecio(precioMueble)
                    || !Validacion.validacionNumeros(unidadesAlmacen)
                    || !Validacion.validacionNumeros(unidadesMinimas)) {
                JOptionPane.showMessageDialog(this, "Existen campos no validos en el formulario.");
                return;
            }
            // Obtener los valores de los otros campos y realizar la validación correspondiente
            // Crear un nuevo objeto Mueble con los valores obtenidos
            Mueble mueble = new Mueble();
            mueble.setIdMueble(codigoMueble);
            mueble.setDescripMueble(txtDescrpMueble.getText());
            mueble.setPrecioUnitario(precioMueble);
            mueble.setUnidadesAlmacen(unidadesAlmacen);
            mueble.setUnidadesMinimas(unidadesMinimas);
            mueble.setTipoMueble(tipoMueble);
            // Intentar grabar el mueble en el archivo
            if (OperacionesFichero.grabarRegistro(mueble)) {
                JOptionPane.showMessageDialog(this, "Mueble grabado exitosamente.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al grabar el mueble.");
            }

            // Limpiar los campos y volver a enfocar txtCodigo
            limpiarDatos();
            txtCodigo.requestFocus();
        } catch (InputMismatchException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "¡ERROR! En los campos numericos debe ser un número entero.");
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Mostramos un cuadro de diálogo de confirmación para preguntar si se quiere salir del programa
        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Quieres salir del programa?",
                "Salir",
                JOptionPane.YES_NO_OPTION);

        // Verificamos la respuesta del usuario
        if (confirmacion == JOptionPane.YES_OPTION) {
            // Si la respuesta es sí, cerramos el programa
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodosActionPerformed
        // Verificamos si el archivo existe
        if (!OperacionesFichero.existeFichero(OperacionesFichero.NOMBRE_ARCHIVO)) {
            // Si el archivo no existe, mostramos un mensaje de error y salimos del método
            JOptionPane.showMessageDialog(this, "El archivo no existe.");
            return;
        }

        // Mostramos un cuadro de diálogo de confirmación para preguntar si se desea borrar el archivo
        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea realmente borrar el archivo de datos?",
                "Borrado de datos",
                JOptionPane.YES_NO_OPTION);

        // Verificamos la respuesta del usuario
        if (confirmacion == JOptionPane.YES_OPTION) {
            // Si la respuesta es sí, intentamos eliminar todos los datos del archivo
            if (!OperacionesFichero.eliminarTodos()) {
                // Si no se pudo borrar el archivo, mostramos un mensaje de error
                JOptionPane.showMessageDialog(this, "No se pudo borrar el archivo.");
            } else {
                // Si se eliminaron los datos correctamente, mostramos un mensaje de éxito
                JOptionPane.showMessageDialog(this, "Archivo eliminado con éxito.");
            }
        }

    }//GEN-LAST:event_btnEliminarTodosActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarDatos();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (!OperacionesFichero.existeFichero(OperacionesFichero.NOMBRE_ARCHIVO)) {
            JOptionPane.showMessageDialog(this, "El archivo no existe.");
            return;
        }
        try {
            // Validar si el campo txtCodigo está vacío
            if (txtCodigo.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "El codigo no puede estar vacío.");
                txtCodigo.requestFocus();
                return;
            }

            // Obtener el valor del campo txtCodigo
            int codigoMueble = Integer.parseInt(txtCodigo.getText());

            // Busca el registro en el archivo
            Mueble mueble = OperacionesFichero.buscarRegistro(codigoMueble);
            if (mueble == null) {
                JOptionPane.showMessageDialog(this, "El mueble introducido no existe.");
                txtCodigo.requestFocus();
            } else {
                visualizarRegistro(mueble);
            }

        } catch (InputMismatchException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "¡ERROR! El codigo debe ser un número entero de 5 cifras como maximo.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarMuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMuebleActionPerformed
        // Verificar si el archivo existe
        if (!OperacionesFichero.existeFichero(OperacionesFichero.NOMBRE_ARCHIVO)) {
            JOptionPane.showMessageDialog(this, "El archivo no existe.");
            return; // Salir del método si el archivo no existe
        }

        try {
            // Validar si el campo txtCodigo está vacío
            if (txtCodigo.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "El código no puede estar vacío.");
                txtCodigo.requestFocus();
                return; // Salir del método si el código está vacío
            }

            // Obtener el valor del campo txtCodigo
            int idMueble = Integer.parseInt(txtCodigo.getText());

            // Buscar el registro en el archivo usando el método buscarRegistro
            Mueble mueble = OperacionesFichero.buscarRegistro(idMueble);
            if (mueble == null) {
                JOptionPane.showMessageDialog(this, "El mueble introducido no existe.");
                txtCodigo.requestFocus();
            } else {
                // Mostrar un cuadro de diálogo de confirmación para borrar el registro
                int confirmacion = JOptionPane.showConfirmDialog(
                        this,
                        "¿Desea realmente borrar este registro?",
                        "Borrar Mueble",
                        JOptionPane.YES_NO_OPTION
                );
                if (confirmacion == JOptionPane.YES_OPTION) {
                    // Si el usuario confirma, intentar eliminar el registro usando el método eliminarRegistro
                    if (!OperacionesFichero.eliminarRegistro(idMueble)) {
                        JOptionPane.showMessageDialog(this, "No se pudo borrar el registro.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Registro eliminado con éxito.");
                    }
                }
            }
        } catch (InputMismatchException | NumberFormatException ex) {
            // Capturar excepciones de tipo InputMismatchException o NumberFormatException
            JOptionPane.showMessageDialog(this, "¡ERROR! El código debe ser un número entero de 5 cifras como máximo.");
        }

    }//GEN-LAST:event_btnEliminarMuebleActionPerformed

    private void btnLimpiarMueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarMueblesActionPerformed
        areaTxt.setText("");

    }//GEN-LAST:event_btnLimpiarMueblesActionPerformed

    private void btnVisualizarMueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarMueblesActionPerformed
        if (!OperacionesFichero.existeFichero(OperacionesFichero.NOMBRE_ARCHIVO)) {
            JOptionPane.showMessageDialog(this, "El archivo no existe.");
            return;
        }
        areaTxt.setText("");
        areaTxt.setText(OperacionesFichero.listarMuebles());

    }//GEN-LAST:event_btnVisualizarMueblesActionPerformed

    private void txtPrecioUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioUnitarioActionPerformed

    // Método para limpiar todos los campos del formulario
    private void limpiarDatos() {
        txtCodigo.setText("");
        txtDescrpMueble.setText("");
        txtPrecioUnitario.setText("");
        txtUnidadesAlmacen.setText("");
        txtUnidadesMinimas.setText("");
        cmbTipoMueble.setSelectedIndex(0); // Establecer el primer índice seleccionado como predeterminado
    }

    // Visualizar los datos del mueble en los campos de la ventana
    private void visualizarRegistro(Mueble mueble) {
        txtCodigo.setText(String.valueOf(mueble.getIdMueble()));
        txtDescrpMueble.setText(mueble.getDescripMueble());
        txtPrecioUnitario.setText(String.valueOf(mueble.getPrecioUnitario()));
        txtUnidadesAlmacen.setText(String.valueOf(mueble.getUnidadesAlmacen()));
        txtUnidadesMinimas.setText(String.valueOf(mueble.getUnidadesMinimas()));
        cmbTipoMueble.setSelectedItem(mueble.getTipoMueble().getTipoMuebleCompleto());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppGestionMueblesDavid.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppGestionMueblesDavid.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppGestionMueblesDavid.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppGestionMueblesDavid.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppGestionMueblesDavid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTxt;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminarMueble;
    private javax.swing.JButton btnEliminarTodos;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarMuebles;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVisualizarMuebles;
    private javax.swing.JComboBox<String> cmbTipoMueble;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescrpMueble;
    private javax.swing.JTextField txtPrecioUnitario;
    private javax.swing.JTextField txtUnidadesAlmacen;
    private javax.swing.JTextField txtUnidadesMinimas;
    // End of variables declaration//GEN-END:variables
}
