/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicios;

import controladores.Operaciones;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelos.Empleado;

/**
 *
 * @author Usuario
 */
public class Ejercicio1_FicheroObjEmpleados extends javax.swing.JFrame {

    // array que almacena los turnos
    static String[] arrayTurno = {"Mañana", "Tarde", "Nocturno", "Mitad"};

    /**
     * Creates new form OperacionesFichero
     */
    public Ejercicio1_FicheroObjEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoEmpleado = new javax.swing.ButtonGroup();
        txtIdEmpleado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNroHijos = new javax.swing.JTextField();
        jRadioIngeniero = new javax.swing.JRadioButton();
        jRadioVendedor = new javax.swing.JRadioButton();
        cboTipoPago = new javax.swing.JComboBox<>();
        txtSalario = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMPLEADOS-NOMINAS");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("ID EMPLEADO");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("NOMBRE");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Nº HIJOS");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("TIPO EMPLEADO ");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("TURNO");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("SALARIO");

        grupoTipoEmpleado.add(jRadioIngeniero);
        jRadioIngeniero.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jRadioIngeniero.setText("Ingeniero");

        grupoTipoEmpleado.add(jRadioVendedor);
        jRadioVendedor.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jRadioVendedor.setText("Vendedor");

        cboTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MAÑANA", "TARDE", "NOCTURNO", "MITAD" }));

        btnGrabar.setBackground(new java.awt.Color(204, 204, 255));
        btnGrabar.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.setOpaque(true);
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(204, 255, 204));
        btnBuscar.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setOpaque(true);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnListar.setBackground(new java.awt.Color(255, 199, 31));
        btnListar.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnListar.setText("Listar Nónimas");
        btnListar.setOpaque(true);
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 0, 204));
        btnSalir.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setOpaque(true);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setOpaque(true);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNroHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioIngeniero)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioVendedor))
                            .addComponent(cboTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnGrabar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(17, 17, 17))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRadioIngeniero, jRadioVendedor});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNroHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioIngeniero)
                        .addComponent(jRadioVendedor)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cboTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGrabar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscar)
                        .addComponent(btnLimpiar)
                        .addComponent(btnListar))
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBuscar, btnGrabar, btnLimpiar, btnListar, btnSalir});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed

        // llamamos al metodo listarNominas de la clase Operaciones
        try {
            Operaciones.listarNominas();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ejercicio1_FicheroObjEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnListarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // llama al metodo limpiarDatos, para limpiar el fromulario
        limpiarDatos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed

        // comprueba que no haya ningun campo vacio o sin seleccionar
        if (algunoVacio(txtIdEmpleado, txtNombre, txtNroHijos, txtSalario) 
            || (!jRadioVendedor.isSelected() && !jRadioIngeniero.isSelected())) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios o sin seleccionar.");
            return;
        }
        // comprueba que el idEmpleado cumpla con el patron establecido
        if (!Operaciones.correcto(txtIdEmpleado.getText(), patronEntero)) {
            JOptionPane.showMessageDialog(null, "El id debe ser de 5 digitos como maximo.");
            txtIdEmpleado.requestFocus();
            return;
        }
        // obtiene el id del formulario y comprueba si ya hay algun empleado con ese id
        int idEmpleado = Integer.parseInt(txtIdEmpleado.getText());
        if (Operaciones.existeEmpleado(idEmpleado)) {
            JOptionPane.showMessageDialog(null, "El empleado existe.");
            txtIdEmpleado.requestFocus();
            return;
        }

        // comprueba que todos los campos cumplan con los patrones requeridos
        if (!Operaciones.correcto(txtNombre.getText(), patronCadena)) {
            JOptionPane.showMessageDialog(null, "El nombre debe tener como maximo 50 caracteres.");
            txtNombre.requestFocus();
            return;

        } else if (!Operaciones.correcto(txtSalario.getText(), patronReal)) {
            JOptionPane.showMessageDialog(null, "El salario de ser un entero de maximo 6 digitos y maximo 2 decimales.");
            txtSalario.requestFocus();
            return;
        } else if (!Operaciones.correcto(txtNroHijos.getText(), patronHijos)) {
            JOptionPane.showMessageDialog(null, "El numero de hijos debe ser de 2 digitos como maximo.");
            txtNroHijos.requestFocus();
            return;
        }
        
        // obtiene los datos del formulario
        String nombre = txtNombre.getText();
        int nroHijos = Integer.parseInt(txtNroHijos.getText());
        float salario = Float.parseFloat(txtSalario.getText());
        
        String tipoEmpleado = "";
        if (jRadioIngeniero.isSelected()) {
            tipoEmpleado = "I";
        } else if (jRadioVendedor.isSelected()) {
            tipoEmpleado = "V";
        }
        int turno = -1;
        int elegirTurno = cboTipoPago.getSelectedIndex();
        switch (elegirTurno) {
            case 0:
                turno = 1;
                break;
            case 1:
                turno = 2;
                break;
            case 2:
                turno = 3;
                break;
            case 3:
                turno = 4;
                break;

        }

        // crea un objeto empleado con los datos del formulario
        Empleado e = new Empleado(idEmpleado, nombre, salario, nroHijos, tipoEmpleado, turno);
        // se guarda el empleado en el fichero
        Operaciones.grabarEmpleado(e);
        // limpia el formulario
        limpiarDatos();
        // pone el foco en el campo idEmpleado
        txtIdEmpleado.requestFocus();
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
         // Mostramos un cuadro de diálogo de confirmación para preguntar si se quiere salir del programa
        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Quieres salir del programa?",
                "Salir",
                JOptionPane.YES_NO_OPTION);

        // Verificamos la respuesta del usuario
        if (confirmacion == JOptionPane.YES_OPTION) {
            // Si la respuesta es sí, cerramos el programa
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      // comprueba que el idEmpleado no este en blanco
        if (txtIdEmpleado.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "ID no puede estar vacio.");
            return;
        }
        // comprueba que el idEmpleado cumpla con el patron
        if (!Operaciones.correcto(txtIdEmpleado.getText(), patronEntero)) {
            JOptionPane.showMessageDialog(null, "El id debe ser de 5 digitos como maximo.");
            txtIdEmpleado.requestFocus();
            return;
        }
        // obtiene el id del formulario y comprueba que exista el empleado
        int idEmpleado = Integer.parseInt(txtIdEmpleado.getText());
        if (!Operaciones.existeEmpleado(idEmpleado)) {
            JOptionPane.showMessageDialog(null, "Registro no existe.");
            txtIdEmpleado.requestFocus();
            return;
        }
        // almacena los datos del empleado encontrado
        Empleado emp = Operaciones.buscaEmpleado(idEmpleado);
        // se visualizan los datos del empleado en el formulario
        visualizarEmpleado(emp);
    }//GEN-LAST:event_btnBuscarActionPerformed
   // patrones que tienen que cumplir los campos del formulario
    Pattern patronCadena = Pattern.compile("[A-Za-z\\d\\s]{1,50}");
    Pattern patronEntero = Pattern.compile("[0-9]{1,5}");
    Pattern patronReal = Pattern.compile("\\d{1,6}(\\.\\d{1,2})?");
    Pattern patronHijos = Pattern.compile("\\d{1,2}");

    // comprueba que no haya ninguna campo vacio en el formulario
    private boolean algunoVacio(JTextField... campos) {
        for (JTextField campo : campos) {
            if (campo.getText().isBlank()) {
                txtIdEmpleado.requestFocus();
                return true;
            }
        }
        return false;
    }

    // limpia los datos del formulario
    private void limpiarDatos() {
        txtIdEmpleado.setText("");
        txtNombre.setText("");
        txtNroHijos.setText("");
        txtSalario.setText("");
        cboTipoPago.setSelectedIndex(0);
    }

    // muestra los datos del empleado en el formulario
    private void visualizarEmpleado(Empleado emp) {
        txtIdEmpleado.setText(String.valueOf(emp.getIdEmpleado()));
        txtNombre.setText(emp.getNombre());
        txtNroHijos.setText(String.valueOf(emp.getNroHijos()));
        txtSalario.setText(String.valueOf(emp.getSalario()));
        if (emp.getTipoEmpleado().equalsIgnoreCase("I")) {
            jRadioIngeniero.setSelected(true);
        } else {
            jRadioVendedor.setSelected(true);
        }
        cboTipoPago.setSelectedIndex(emp.getTurno());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1_FicheroObjEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1_FicheroObjEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1_FicheroObjEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1_FicheroObjEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio1_FicheroObjEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboTipoPago;
    private javax.swing.ButtonGroup grupoTipoEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioIngeniero;
    private javax.swing.JRadioButton jRadioVendedor;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNroHijos;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
